FROM nvcr.io/nvidia/isaac-sim:5.1.0

USER root

# Install necessary packages
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    nano \
    curl \
    wget \
    python3-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*