import json
import os
import glob
import argparse
import numpy as np
from PIL import Image

CLASS_MAP = {
    "person": 0, "vehicle": 1, "hardhat": 2, "vest": 3,
    "rack": 4, "pallet": 5, "box": 6, "barrel": 7,
    "cone": 8, "pillar": 9, "sign": 10, "fire_extinguisher": 11,
    "cart": 12,
    "hazard_zone_warning": 13, "hazard_zone_restricted": 14, "hazard_zone_critical": 15,
}

REVERSE_CLASS_MAP = {v: k for k, v in CLASS_MAP.items()}


def _load_id_to_label(dataset_dir):
    label_file = os.path.join(dataset_dir, "semantic_id_to_labels.json")
    id_to_label = {}
    if os.path.exists(label_file):
        raw = json.load(open(label_file))
        for k, v in raw.items():
            label = v["class"] if isinstance(v, dict) else v
            id_to_label[int(k)] = label
    else:
        print(f"Warning: {label_file} not found; trying instance_segmentation_colors.json fallback.")
        colors_file = os.path.join(dataset_dir, "instance_segmentation_colors.json")
        if os.path.exists(colors_file):
            colors_raw = json.load(open(colors_file))
            for entry in colors_raw:
                class_name = entry.get("class", "")
                color = tuple(entry.get("color", []))
                class_id = CLASS_MAP.get(class_name.lower(), -1)
                if class_id >= 0:
                    id_to_label[class_id] = class_name
            print(f"  Loaded {len(id_to_label)} class mappings from colors JSON.")
        else:
            print("Warning: No semantic mapping files found. Will attempt direct class name lookup from bbox data.")
    return id_to_label


def _colors_json_to_label_map(colors_path):
    if not os.path.exists(colors_path):
        return {}
    raw = json.load(open(colors_path))
    color_to_class_id = {}
    for entry in raw:
        color = tuple(entry.get("color", []))
        class_name = entry.get("class", "")
        class_id = CLASS_MAP.get(class_name.lower(), -1)
        if class_id >= 0:
            color_to_class_id[color] = class_id
    return color_to_class_id


def convert_npy_to_yolo(dataset_dir="/tmp/dataset"):
    npy_files = sorted(glob.glob(os.path.join(dataset_dir, "bounding_box_2d_tight_*.npy")))

    if not npy_files:
        print(f"Warning: No .npy files found in {dataset_dir}. Ensure BasicWriter has written output.")
        return

    id_to_label = _load_id_to_label(dataset_dir)
    has_json_mapping = bool(id_to_label)

    converted = 0
    total_bboxes = 0
    skipped_bboxes = 0
    for npy_path in npy_files:
        basename = os.path.splitext(os.path.basename(npy_path))[0]
        frame_str = basename.split("_")[-1]

        rgb_path = os.path.join(dataset_dir, f"rgb_{frame_str}.png")
        if not os.path.exists(rgb_path):
            print(f"Warning: RGB image not found for frame {frame_str}, skipping.")
            continue

        with Image.open(rgb_path) as img:
            img_width, img_height = img.size

        bboxes = np.load(npy_path, allow_pickle=True)

        txt_path = os.path.join(dataset_dir, f"rgb_{frame_str}.txt")
        with open(txt_path, "w") as txt_f:
            for row in bboxes:
                total_bboxes += 1
                x_min = float(row["x_min"])
                y_min = float(row["y_min"])
                x_max = float(row["x_max"])
                y_max = float(row["y_max"])

                label = ""
                if has_json_mapping:
                    semantic_id = int(row["semanticId"])
                    label = id_to_label.get(semantic_id, "")
                if not label and "class" in row.dtype.names:
                    raw = row["class"]
                    label = raw.decode() if isinstance(raw, bytes) else str(raw)
                if not label and "semanticId" in row.dtype.names:
                    semantic_id = int(row["semanticId"])
                    label = id_to_label.get(semantic_id, "")
                class_id = CLASS_MAP.get(label.lower(), -1)
                if class_id == -1:
                    skipped_bboxes += 1
                    continue

                x_center = (x_min + x_max) / 2.0 / img_width
                y_center = (y_min + y_max) / 2.0 / img_height
                width = (x_max - x_min) / img_width
                height = (y_max - y_min) / img_height

                txt_f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")

        converted += 1

    print(f"Successfully converted {converted} frames to YOLO format in {dataset_dir}")
    print(f"  Total bounding boxes: {total_bboxes}, Skipped (unresolved class): {skipped_bboxes}")
    if skipped_bboxes > 0 and not has_json_mapping:
        print("  Hint: Ensure semantic_id_to_labels.json is generated by BasicWriter.")
        print("  Check that all prims have USD-level semantic:Semantics:params:semanticData attributes.")
    print(f"  Total bounding boxes: {total_bboxes}, Skipped (unresolved class): {skipped_bboxes}")
    if skipped_bboxes > 0 and not has_json_mapping:
        print("  Hint: Ensure semantic_id_to_labels.json is generated by BasicWriter.")
        print("  Check that all prims have USD-level semantic:Semantics:params:semanticData attributes.")


def convert_instance_masks(dataset_dir="/tmp/dataset"):
    seg_files = sorted(glob.glob(os.path.join(dataset_dir, "instance_segmentation_*.png")))
    if not seg_files:
        print("Warning: No instance segmentation files found. Skipping mask conversion.")
        return 0

    colors_json = os.path.join(dataset_dir, "instance_segmentation_colors.json")
    color_to_class_id = _colors_json_to_label_map(colors_json)
    if not color_to_class_id:
        print("Warning: No valid color-to-class mapping found. Skipping mask conversion.")
        return 0

    converted = 0
    for seg_path in seg_files:
        basename = os.path.splitext(os.path.basename(seg_path))[0]
        frame_str = basename.split("_")[-1]

        rgb_path = os.path.join(dataset_dir, f"rgb_{frame_str}.png")
        if not os.path.exists(rgb_path):
            continue

        with Image.open(rgb_path) as img:
            img_width, img_height = img.size

        seg_img = Image.open(seg_path).convert("RGB")
        seg_array = np.array(seg_img)

        mask_dir = os.path.join(dataset_dir, "masks")
        os.makedirs(mask_dir, exist_ok=True)

        mask_txt = os.path.join(mask_dir, f"rgb_{frame_str}.txt")

        found_instances = {}
        for color, class_id in color_to_class_id.items():
            match = (seg_array[:, :, 0] == color[0]) & \
                    (seg_array[:, :, 1] == color[1]) & \
                    (seg_array[:, :, 2] == color[2])
            if np.any(match):
                found_instances[class_id] = match

        if not found_instances:
            converted += 1
            continue

        with open(mask_txt, "w") as f:
            for class_id, match in found_instances.items():
                class_name = REVERSE_CLASS_MAP[class_id]
                mask_filename = f"{class_name}_{class_id:02d}_{frame_str}.png"
                mask_path = os.path.join(mask_dir, mask_filename)

                mask = (match * 255).astype(np.uint8)
                mask_img = Image.fromarray(mask, mode="L")
                mask_img.save(mask_path)

                coords = np.column_stack(np.where(match))
                if len(coords) > 0:
                    y_min, x_min = coords.min(axis=0)
                    y_max, x_max = coords.max(axis=0)
                    x_center = (x_min + x_max) / 2.0 / img_width
                    y_center = (y_min + y_max) / 2.0 / img_height
                    width = (x_max - x_min) / img_width
                    height = (y_max - y_min) / img_height
                    f.write(f"{class_id} {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f} {mask_filename}\n")

        converted += 1

    print(f"Successfully converted {converted} frames to YOLO instance masks in {dataset_dir}/masks/")
    return converted


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert CocoWriter output to YOLO format.")
    parser.add_argument("--dir", type=str, default="/tmp/dataset", help="Directory containing CocoWriter output.")
    parser.add_argument("--masks", action="store_true", help="Also convert instance segmentation to YOLO mask format.")
    args = parser.parse_args()
    convert_npy_to_yolo(args.dir)
    if args.masks:
        convert_instance_masks(args.dir)
